### PR TITLE
[feat] Add Github Actions

### PR DESCRIPTION
**Pull request by hgruniaux**
Actually the action only configure and build the project. Not running or testing is done.

### CODE REVIEW

**Comment by hgruniaux** [comment]
Actually we have the same errors as on the ENS computers. The C++20 class `std::source_location` is not supported by GCC 11 (the version used by the ENS computers and Github)...

**Comment by hgruniaux** [comment]
I hate baremetal developpment...

**Comment by hgruniaux** [comment]
For now, we can disable clang-tidy, or use custom targets that call clang-tidy with custom arguments. The problem seems to be CMake that is not able to provide enough information to clang.

What you think ?

**Comment by hgruniaux** [comment]
Maybe add 
```cmake
if(CMAKE_EXPORT_COMPILE_COMMANDS)
    set(CMAKE_CXX_STANDARD_INCLUDE_DIRECTORIES ${CMAKE_CXX_IMPLICIT_INCLUDE_DIRECTORIES})
endif()
```
See https://stackoverflow.com/questions/20587228/clang-error-stddef-file-not-found

**Comment by desfreng** [comment]
It works on my machine. I was able to reproduce `clang-tidy` error about directories includes. And I have find a workaround. I think my workaround does not works because of the version of clang-tidy...

**Comment by hgruniaux** [comment]
And what is exactly your workaround ? Do you have tested the above solution ?

**Comment by desfreng** [comment]
To manually add include dirs in a environment variables. The bug is in clang-tidy, cmake works as expected.

**Comment by hgruniaux** [comment]
IT WORKS (at least in Debug mode).
Still remains some cleanup and fixing release mode

**Comment by hgruniaux** [comment]
This is not perfect. But it works.

**Comment by desfreng** [comment]
Good work ! Can I make the include dirs not hard-coded ?

**Comment by desfreng** [comment]
Whoouuuu Youpi !

**Review by desfreng — APPROVED** [review]

**Pull request merged**
